# Generated by Django 2.0.2 on 2018-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoSiteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsubtopic', models.IntegerField(db_column='idSubTopic')),
                ('name', models.TextField()),
                ('topicid', models.IntegerField(db_column='topicId')),
            ],
            options={
                'db_table': 'subTopic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtopic', models.IntegerField(db_column='idTopic')),
                ('name', models.TextField()),
                ('subjectid', models.IntegerField(db_column='subjectId')),
            ],
            options={
                'db_table': 'topic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idvideo', models.IntegerField(db_column='idVideo')),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('channelurl', models.TextField(db_column='channelUrl')),
                ('numberofviews', models.IntegerField(blank=True, db_column='numberOfViews', null=True)),
                ('date', models.TextField()),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('dislikes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
    ]
