# Generated by Django 2.0.2 on 2018-03-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoSiteApp', '0002_subtopic_topic_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('idsurvey', models.IntegerField(db_column='idSurvey', primary_key=True, serialize=False)),
                ('relevant', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('mistakes', models.IntegerField(blank=True, null=True)),
                ('presentation', models.IntegerField(blank=True, null=True)),
                ('informative', models.IntegerField(blank=True, null=True)),
                ('quality', models.IntegerField(blank=True, null=True)),
                ('videoid', models.IntegerField(db_column='videoId')),
            ],
            options={
                'db_table': 'survey',
                'managed': False,
            },
        ),
    ]
